### ISSUE TITLE
Change dependency to use https://github.com/poise/application_javascript

### ISSUE THREAD

**Issue by jonricaurte** [Mindera/pm2-cookbook#18]
Right now pm2 cookbook uses https://github.com/redguide/nodejs/ as a dependency. 

For later versions of node and chef, this doesn't work out that well. Can the dependency be https://github.com/poise/application_javascript instead? Even Amazon is using that as the boilerplate for chef 12 and nodejs:

https://github.com/awslabs/opsworks-linux-demo-cookbook-nodejs

**Comment by Dynamo6** [comment]
+1 I'm trying to use the pm2_cookbook with Opsworks and currently getting nowhere

**Comment by miguelcnf** [comment]
Hi all, sorry for not getting back at this earlier but I've been busy in another world. Let me try and give it some time this week.

**Comment by miguelcnf** [comment]
I didn't use `application_javascript` as that's intended to run node applications via npm start scripts.

I've updated it to use `poise-javascript` instead of `nodejs` instead, which allows us to install the node runtime and noe packages as we wish - I did have to link executable into the system path in order to maintain retrocompatibility.

@Dynamo6 @jonricaurte can you give the [usePoiseJavascript](https://github.com/Mindera/pm2-cookbook/tree/usePoiseJavascript) branch a go?

**Comment by miguelcnf** [comment]
Released version `0.7.0` to supermarket which should fix this.

Re-open if you still think this needs more work.

**Comment by jonricaurte** [comment]
@miguelcnf awesome thanks!
